services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
    command: >
      sh -c "
      until pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      alembic -c /app/alembic.ini revision --autogenerate -m 'add migrations' &&
      alembic -c /app/alembic.ini upgrade head &&
      uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge
